baseurl = "http://edu.rosborough.ca/"
languageCode = "en-us"
title = "Dave Rosborough"
theme = "hyde"

[params]
  description = "Thoughts on education and technology"
  copyright = "Copyright © 2015 Dave Rosborough.  All Rights Reserved."